// Code generated by ent, DO NOT EDIT.

package periodictask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/hedgehog125/project-reboot/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldEQ(FieldName, v))
}

// LastRan applies equality check predicate on the "lastRan" field. It's identical to LastRanEQ.
func LastRan(v time.Time) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldEQ(FieldLastRan, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldContainsFold(FieldName, v))
}

// LastRanEQ applies the EQ predicate on the "lastRan" field.
func LastRanEQ(v time.Time) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldEQ(FieldLastRan, v))
}

// LastRanNEQ applies the NEQ predicate on the "lastRan" field.
func LastRanNEQ(v time.Time) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldNEQ(FieldLastRan, v))
}

// LastRanIn applies the In predicate on the "lastRan" field.
func LastRanIn(vs ...time.Time) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldIn(FieldLastRan, vs...))
}

// LastRanNotIn applies the NotIn predicate on the "lastRan" field.
func LastRanNotIn(vs ...time.Time) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldNotIn(FieldLastRan, vs...))
}

// LastRanGT applies the GT predicate on the "lastRan" field.
func LastRanGT(v time.Time) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldGT(FieldLastRan, v))
}

// LastRanGTE applies the GTE predicate on the "lastRan" field.
func LastRanGTE(v time.Time) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldGTE(FieldLastRan, v))
}

// LastRanLT applies the LT predicate on the "lastRan" field.
func LastRanLT(v time.Time) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldLT(FieldLastRan, v))
}

// LastRanLTE applies the LTE predicate on the "lastRan" field.
func LastRanLTE(v time.Time) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldLTE(FieldLastRan, v))
}

// LastRanIsNil applies the IsNil predicate on the "lastRan" field.
func LastRanIsNil() predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldIsNull(FieldLastRan))
}

// LastRanNotNil applies the NotNil predicate on the "lastRan" field.
func LastRanNotNil() predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.FieldNotNull(FieldLastRan))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PeriodicTask) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PeriodicTask) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PeriodicTask) predicate.PeriodicTask {
	return predicate.PeriodicTask(sql.NotPredicates(p))
}
