// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldAlertDiscordId holds the string denoting the alertdiscordid field in the database.
	FieldAlertDiscordId = "alert_discord_id"
	// FieldAlertEmail holds the string denoting the alertemail field in the database.
	FieldAlertEmail = "alert_email"
	// FieldLocked holds the string denoting the locked field in the database.
	FieldLocked = "locked"
	// FieldLockedUntil holds the string denoting the lockeduntil field in the database.
	FieldLockedUntil = "locked_until"
	// FieldSessionsValidFrom holds the string denoting the sessionsvalidfrom field in the database.
	FieldSessionsValidFrom = "sessions_valid_from"
	// EdgeStash holds the string denoting the stash edge name in mutations.
	EdgeStash = "stash"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgeLogs holds the string denoting the logs edge name in mutations.
	EdgeLogs = "logs"
	// Table holds the table name of the user in the database.
	Table = "users"
	// StashTable is the table that holds the stash relation/edge.
	StashTable = "stashes"
	// StashInverseTable is the table name for the Stash entity.
	// It exists in this package in order to avoid circular dependency with the "stash" package.
	StashInverseTable = "stashes"
	// StashColumn is the table column denoting the stash relation/edge.
	StashColumn = "user_id"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "sessions"
	// SessionsInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionsInverseTable = "sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "user_id"
	// LogsTable is the table that holds the logs relation/edge.
	LogsTable = "log_entries"
	// LogsInverseTable is the table name for the LogEntry entity.
	// It exists in this package in order to avoid circular dependency with the "logentry" package.
	LogsInverseTable = "log_entries"
	// LogsColumn is the table column denoting the logs relation/edge.
	LogsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldAlertDiscordId,
	FieldAlertEmail,
	FieldLocked,
	FieldLockedUntil,
	FieldSessionsValidFrom,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// DefaultAlertDiscordId holds the default value on creation for the "alertDiscordId" field.
	DefaultAlertDiscordId string
	// DefaultAlertEmail holds the default value on creation for the "alertEmail" field.
	DefaultAlertEmail string
	// DefaultLocked holds the default value on creation for the "locked" field.
	DefaultLocked bool
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByAlertDiscordId orders the results by the alertDiscordId field.
func ByAlertDiscordId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertDiscordId, opts...).ToFunc()
}

// ByAlertEmail orders the results by the alertEmail field.
func ByAlertEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlertEmail, opts...).ToFunc()
}

// ByLocked orders the results by the locked field.
func ByLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocked, opts...).ToFunc()
}

// ByLockedUntil orders the results by the lockedUntil field.
func ByLockedUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedUntil, opts...).ToFunc()
}

// BySessionsValidFrom orders the results by the sessionsValidFrom field.
func BySessionsValidFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionsValidFrom, opts...).ToFunc()
}

// ByStashField orders the results by stash field.
func ByStashField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStashStep(), sql.OrderByField(field, opts...))
	}
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLogsCount orders the results by logs count.
func ByLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLogsStep(), opts...)
	}
}

// ByLogs orders the results by logs terms.
func ByLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStashStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StashInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, StashTable, StashColumn),
	)
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
func newLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LogsTable, LogsColumn),
	)
}
