// Code generated by ent, DO NOT EDIT.

package stash

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the stash type in the database.
	Label = "stash"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldFileName holds the string denoting the filename field in the database.
	FieldFileName = "file_name"
	// FieldMime holds the string denoting the mime field in the database.
	FieldMime = "mime"
	// FieldNonce holds the string denoting the nonce field in the database.
	FieldNonce = "nonce"
	// FieldKeySalt holds the string denoting the keysalt field in the database.
	FieldKeySalt = "key_salt"
	// FieldHashTime holds the string denoting the hashtime field in the database.
	FieldHashTime = "hash_time"
	// FieldHashMemory holds the string denoting the hashmemory field in the database.
	FieldHashMemory = "hash_memory"
	// FieldHashThreads holds the string denoting the hashthreads field in the database.
	FieldHashThreads = "hash_threads"
	// FieldUserID holds the string denoting the userid field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the stash in the database.
	Table = "stashes"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "stashes"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for stash fields.
var Columns = []string{
	FieldID,
	FieldContent,
	FieldFileName,
	FieldMime,
	FieldNonce,
	FieldKeySalt,
	FieldHashTime,
	FieldHashMemory,
	FieldHashThreads,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func([]byte) error
	// FileNameValidator is a validator for the "fileName" field. It is called by the builders before save.
	FileNameValidator func(string) error
	// MimeValidator is a validator for the "mime" field. It is called by the builders before save.
	MimeValidator func(string) error
	// NonceValidator is a validator for the "nonce" field. It is called by the builders before save.
	NonceValidator func([]byte) error
	// KeySaltValidator is a validator for the "keySalt" field. It is called by the builders before save.
	KeySaltValidator func([]byte) error
)

// OrderOption defines the ordering options for the Stash queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFileName orders the results by the fileName field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByMime orders the results by the mime field.
func ByMime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMime, opts...).ToFunc()
}

// ByHashTime orders the results by the hashTime field.
func ByHashTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHashTime, opts...).ToFunc()
}

// ByHashMemory orders the results by the hashMemory field.
func ByHashMemory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHashMemory, opts...).ToFunc()
}

// ByHashThreads orders the results by the hashThreads field.
func ByHashThreads(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHashThreads, opts...).ToFunc()
}

// ByUserID orders the results by the userID field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
