// Code generated by ent, DO NOT EDIT.

package job

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the job type in the database.
	Label = "job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldDueAt holds the string denoting the dueat field in the database.
	FieldDueAt = "due_at"
	// FieldOriginallyDueAt holds the string denoting the originallydueat field in the database.
	FieldOriginallyDueAt = "originally_due_at"
	// FieldStartedAt holds the string denoting the startedat field in the database.
	FieldStartedAt = "started_at"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRetries holds the string denoting the retries field in the database.
	FieldRetries = "retries"
	// FieldRetriedFraction holds the string denoting the retriedfraction field in the database.
	FieldRetriedFraction = "retried_fraction"
	// FieldLoggedStallWarning holds the string denoting the loggedstallwarning field in the database.
	FieldLoggedStallWarning = "logged_stall_warning"
	// Table holds the table name of the job in the database.
	Table = "jobs"
)

// Columns holds all SQL columns for job fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldDueAt,
	FieldOriginallyDueAt,
	FieldStartedAt,
	FieldType,
	FieldVersion,
	FieldPriority,
	FieldWeight,
	FieldBody,
	FieldStatus,
	FieldRetries,
	FieldRetriedFraction,
	FieldLoggedStallWarning,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultRetries holds the default value on creation for the "retries" field.
	DefaultRetries int
	// DefaultRetriedFraction holds the default value on creation for the "retriedFraction" field.
	DefaultRetriedFraction float64
	// DefaultLoggedStallWarning holds the default value on creation for the "loggedStallWarning" field.
	DefaultLoggedStallWarning bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending Status = "pending"
	StatusRunning Status = "running"
	StatusFailed  Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusRunning, StatusFailed:
		return nil
	default:
		return fmt.Errorf("job: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Job queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDueAt orders the results by the dueAt field.
func ByDueAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDueAt, opts...).ToFunc()
}

// ByOriginallyDueAt orders the results by the originallyDueAt field.
func ByOriginallyDueAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginallyDueAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the startedAt field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRetries orders the results by the retries field.
func ByRetries(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetries, opts...).ToFunc()
}

// ByRetriedFraction orders the results by the retriedFraction field.
func ByRetriedFraction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetriedFraction, opts...).ToFunc()
}

// ByLoggedStallWarning orders the results by the loggedStallWarning field.
func ByLoggedStallWarning(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoggedStallWarning, opts...).ToFunc()
}
