// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/NicoClack/cryptic-stash/backend/ent/job"
	"github.com/google/uuid"
)

// Job is the model entity for the Job schema.
type Job struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// DueAt holds the value of the "dueAt" field.
	DueAt time.Time `json:"dueAt,omitempty"`
	// OriginallyDueAt holds the value of the "originallyDueAt" field.
	OriginallyDueAt time.Time `json:"originallyDueAt,omitempty"`
	// StartedAt holds the value of the "startedAt" field.
	StartedAt time.Time `json:"startedAt,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int8 `json:"priority,omitempty"`
	// Weight holds the value of the "weight" field.
	Weight int `json:"weight,omitempty"`
	// Body holds the value of the "body" field.
	Body json.RawMessage `json:"body,omitempty"`
	// Status holds the value of the "status" field.
	Status job.Status `json:"status,omitempty"`
	// Retries holds the value of the "retries" field.
	Retries int `json:"retries,omitempty"`
	// RetriedFraction holds the value of the "retriedFraction" field.
	RetriedFraction float64 `json:"retriedFraction,omitempty"`
	// LoggedStallWarning holds the value of the "loggedStallWarning" field.
	LoggedStallWarning bool `json:"loggedStallWarning,omitempty"`
	selectValues       sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Job) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case job.FieldBody:
			values[i] = new([]byte)
		case job.FieldLoggedStallWarning:
			values[i] = new(sql.NullBool)
		case job.FieldRetriedFraction:
			values[i] = new(sql.NullFloat64)
		case job.FieldVersion, job.FieldPriority, job.FieldWeight, job.FieldRetries:
			values[i] = new(sql.NullInt64)
		case job.FieldType, job.FieldStatus:
			values[i] = new(sql.NullString)
		case job.FieldCreatedAt, job.FieldDueAt, job.FieldOriginallyDueAt, job.FieldStartedAt:
			values[i] = new(sql.NullTime)
		case job.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Job fields.
func (_m *Job) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case job.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case job.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case job.FieldDueAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dueAt", values[i])
			} else if value.Valid {
				_m.DueAt = value.Time
			}
		case job.FieldOriginallyDueAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field originallyDueAt", values[i])
			} else if value.Valid {
				_m.OriginallyDueAt = value.Time
			}
		case job.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field startedAt", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case job.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case job.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case job.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int8(value.Int64)
			}
		case job.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case job.FieldBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Body); err != nil {
					return fmt.Errorf("unmarshal field body: %w", err)
				}
			}
		case job.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = job.Status(value.String)
			}
		case job.FieldRetries:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retries", values[i])
			} else if value.Valid {
				_m.Retries = int(value.Int64)
			}
		case job.FieldRetriedFraction:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field retriedFraction", values[i])
			} else if value.Valid {
				_m.RetriedFraction = value.Float64
			}
		case job.FieldLoggedStallWarning:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field loggedStallWarning", values[i])
			} else if value.Valid {
				_m.LoggedStallWarning = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Job.
// This includes values selected through modifiers, order, etc.
func (_m *Job) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Job.
// Note that you need to call Job.Unwrap() before calling this method if this Job
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Job) Update() *JobUpdateOne {
	return NewJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Job entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Job) Unwrap() *Job {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Job is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Job) String() string {
	var builder strings.Builder
	builder.WriteString("Job(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("dueAt=")
	builder.WriteString(_m.DueAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("originallyDueAt=")
	builder.WriteString(_m.OriginallyDueAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("startedAt=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(fmt.Sprintf("%v", _m.Body))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("retries=")
	builder.WriteString(fmt.Sprintf("%v", _m.Retries))
	builder.WriteString(", ")
	builder.WriteString("retriedFraction=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetriedFraction))
	builder.WriteString(", ")
	builder.WriteString("loggedStallWarning=")
	builder.WriteString(fmt.Sprintf("%v", _m.LoggedStallWarning))
	builder.WriteByte(')')
	return builder.String()
}

// Jobs is a parsable slice of Job.
type Jobs []*Job
