// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NicoClack/cryptic-stash/backend/ent/keyvalue"
	"github.com/google/uuid"
)

// KeyValueCreate is the builder for creating a KeyValue entity.
type KeyValueCreate struct {
	config
	mutation *KeyValueMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (_c *KeyValueCreate) SetKey(v string) *KeyValueCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *KeyValueCreate) SetValue(v json.RawMessage) *KeyValueCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetID sets the "id" field.
func (_c *KeyValueCreate) SetID(v uuid.UUID) *KeyValueCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *KeyValueCreate) SetNillableID(v *uuid.UUID) *KeyValueCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the KeyValueMutation object of the builder.
func (_c *KeyValueCreate) Mutation() *KeyValueMutation {
	return _c.mutation
}

// Save creates the KeyValue in the database.
func (_c *KeyValueCreate) Save(ctx context.Context) (*KeyValue, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KeyValueCreate) SaveX(ctx context.Context) *KeyValue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KeyValueCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KeyValueCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KeyValueCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := keyvalue.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KeyValueCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "KeyValue.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := keyvalue.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "KeyValue.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "KeyValue.value"`)}
	}
	return nil
}

func (_c *KeyValueCreate) sqlSave(ctx context.Context) (*KeyValue, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KeyValueCreate) createSpec() (*KeyValue, *sqlgraph.CreateSpec) {
	var (
		_node = &KeyValue{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(keyvalue.Table, sqlgraph.NewFieldSpec(keyvalue.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(keyvalue.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(keyvalue.FieldValue, field.TypeJSON, value)
		_node.Value = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.KeyValue.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KeyValueUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *KeyValueCreate) OnConflict(opts ...sql.ConflictOption) *KeyValueUpsertOne {
	_c.conflict = opts
	return &KeyValueUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.KeyValue.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KeyValueCreate) OnConflictColumns(columns ...string) *KeyValueUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KeyValueUpsertOne{
		create: _c,
	}
}

type (
	// KeyValueUpsertOne is the builder for "upsert"-ing
	//  one KeyValue node.
	KeyValueUpsertOne struct {
		create *KeyValueCreate
	}

	// KeyValueUpsert is the "OnConflict" setter.
	KeyValueUpsert struct {
		*sql.UpdateSet
	}
)

// SetKey sets the "key" field.
func (u *KeyValueUpsert) SetKey(v string) *KeyValueUpsert {
	u.Set(keyvalue.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *KeyValueUpsert) UpdateKey() *KeyValueUpsert {
	u.SetExcluded(keyvalue.FieldKey)
	return u
}

// SetValue sets the "value" field.
func (u *KeyValueUpsert) SetValue(v json.RawMessage) *KeyValueUpsert {
	u.Set(keyvalue.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *KeyValueUpsert) UpdateValue() *KeyValueUpsert {
	u.SetExcluded(keyvalue.FieldValue)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.KeyValue.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(keyvalue.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KeyValueUpsertOne) UpdateNewValues() *KeyValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(keyvalue.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.KeyValue.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *KeyValueUpsertOne) Ignore() *KeyValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KeyValueUpsertOne) DoNothing() *KeyValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KeyValueCreate.OnConflict
// documentation for more info.
func (u *KeyValueUpsertOne) Update(set func(*KeyValueUpsert)) *KeyValueUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KeyValueUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *KeyValueUpsertOne) SetKey(v string) *KeyValueUpsertOne {
	return u.Update(func(s *KeyValueUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *KeyValueUpsertOne) UpdateKey() *KeyValueUpsertOne {
	return u.Update(func(s *KeyValueUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *KeyValueUpsertOne) SetValue(v json.RawMessage) *KeyValueUpsertOne {
	return u.Update(func(s *KeyValueUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *KeyValueUpsertOne) UpdateValue() *KeyValueUpsertOne {
	return u.Update(func(s *KeyValueUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *KeyValueUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KeyValueCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KeyValueUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *KeyValueUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: KeyValueUpsertOne.ID is not supported by MySQL driver. Use KeyValueUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *KeyValueUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// KeyValueCreateBulk is the builder for creating many KeyValue entities in bulk.
type KeyValueCreateBulk struct {
	config
	err      error
	builders []*KeyValueCreate
	conflict []sql.ConflictOption
}

// Save creates the KeyValue entities in the database.
func (_c *KeyValueCreateBulk) Save(ctx context.Context) ([]*KeyValue, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*KeyValue, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KeyValueMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KeyValueCreateBulk) SaveX(ctx context.Context) []*KeyValue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KeyValueCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KeyValueCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.KeyValue.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KeyValueUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *KeyValueCreateBulk) OnConflict(opts ...sql.ConflictOption) *KeyValueUpsertBulk {
	_c.conflict = opts
	return &KeyValueUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.KeyValue.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KeyValueCreateBulk) OnConflictColumns(columns ...string) *KeyValueUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KeyValueUpsertBulk{
		create: _c,
	}
}

// KeyValueUpsertBulk is the builder for "upsert"-ing
// a bulk of KeyValue nodes.
type KeyValueUpsertBulk struct {
	create *KeyValueCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.KeyValue.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(keyvalue.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KeyValueUpsertBulk) UpdateNewValues() *KeyValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(keyvalue.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.KeyValue.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *KeyValueUpsertBulk) Ignore() *KeyValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KeyValueUpsertBulk) DoNothing() *KeyValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KeyValueCreateBulk.OnConflict
// documentation for more info.
func (u *KeyValueUpsertBulk) Update(set func(*KeyValueUpsert)) *KeyValueUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KeyValueUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *KeyValueUpsertBulk) SetKey(v string) *KeyValueUpsertBulk {
	return u.Update(func(s *KeyValueUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *KeyValueUpsertBulk) UpdateKey() *KeyValueUpsertBulk {
	return u.Update(func(s *KeyValueUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *KeyValueUpsertBulk) SetValue(v json.RawMessage) *KeyValueUpsertBulk {
	return u.Update(func(s *KeyValueUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *KeyValueUpsertBulk) UpdateValue() *KeyValueUpsertBulk {
	return u.Update(func(s *KeyValueUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *KeyValueUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the KeyValueCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KeyValueCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KeyValueUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
