// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/NicoClack/cryptic-stash/backend/ent/job"
	"github.com/NicoClack/cryptic-stash/backend/ent/keyvalue"
	"github.com/NicoClack/cryptic-stash/backend/ent/logentry"
	"github.com/NicoClack/cryptic-stash/backend/ent/loginalert"
	"github.com/NicoClack/cryptic-stash/backend/ent/periodictask"
	"github.com/NicoClack/cryptic-stash/backend/ent/schema"
	"github.com/NicoClack/cryptic-stash/backend/ent/session"
	"github.com/NicoClack/cryptic-stash/backend/ent/stash"
	"github.com/NicoClack/cryptic-stash/backend/ent/twofactoraction"
	"github.com/NicoClack/cryptic-stash/backend/ent/user"
	"github.com/NicoClack/cryptic-stash/backend/ent/usermessenger"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescType is the schema descriptor for type field.
	jobDescType := jobFields[5].Descriptor()
	// job.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	job.TypeValidator = func() func(string) error {
		validators := jobDescType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_type string) error {
			for _, fn := range fns {
				if err := fn(_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// jobDescRetries is the schema descriptor for retries field.
	jobDescRetries := jobFields[11].Descriptor()
	// job.DefaultRetries holds the default value on creation for the retries field.
	job.DefaultRetries = jobDescRetries.Default.(int)
	// jobDescRetriedFraction is the schema descriptor for retriedFraction field.
	jobDescRetriedFraction := jobFields[12].Descriptor()
	// job.DefaultRetriedFraction holds the default value on creation for the retriedFraction field.
	job.DefaultRetriedFraction = jobDescRetriedFraction.Default.(float64)
	// jobDescLoggedStallWarning is the schema descriptor for loggedStallWarning field.
	jobDescLoggedStallWarning := jobFields[13].Descriptor()
	// job.DefaultLoggedStallWarning holds the default value on creation for the loggedStallWarning field.
	job.DefaultLoggedStallWarning = jobDescLoggedStallWarning.Default.(bool)
	// jobDescID is the schema descriptor for id field.
	jobDescID := jobFields[0].Descriptor()
	// job.DefaultID holds the default value on creation for the id field.
	job.DefaultID = jobDescID.Default.(func() uuid.UUID)
	keyvalueFields := schema.KeyValue{}.Fields()
	_ = keyvalueFields
	// keyvalueDescKey is the schema descriptor for key field.
	keyvalueDescKey := keyvalueFields[1].Descriptor()
	// keyvalue.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	keyvalue.KeyValidator = func() func(string) error {
		validators := keyvalueDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// keyvalueDescID is the schema descriptor for id field.
	keyvalueDescID := keyvalueFields[0].Descriptor()
	// keyvalue.DefaultID holds the default value on creation for the id field.
	keyvalue.DefaultID = keyvalueDescID.Default.(func() uuid.UUID)
	logentryFields := schema.LogEntry{}.Fields()
	_ = logentryFields
	// logentryDescID is the schema descriptor for id field.
	logentryDescID := logentryFields[0].Descriptor()
	// logentry.DefaultID holds the default value on creation for the id field.
	logentry.DefaultID = logentryDescID.Default.(func() uuid.UUID)
	loginalertFields := schema.LoginAlert{}.Fields()
	_ = loginalertFields
	// loginalertDescVersionedMessengerType is the schema descriptor for versionedMessengerType field.
	loginalertDescVersionedMessengerType := loginalertFields[2].Descriptor()
	// loginalert.VersionedMessengerTypeValidator is a validator for the "versionedMessengerType" field. It is called by the builders before save.
	loginalert.VersionedMessengerTypeValidator = func() func(string) error {
		validators := loginalertDescVersionedMessengerType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(versionedMessengerType string) error {
			for _, fn := range fns {
				if err := fn(versionedMessengerType); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// loginalertDescID is the schema descriptor for id field.
	loginalertDescID := loginalertFields[0].Descriptor()
	// loginalert.DefaultID holds the default value on creation for the id field.
	loginalert.DefaultID = loginalertDescID.Default.(func() uuid.UUID)
	periodictaskFields := schema.PeriodicTask{}.Fields()
	_ = periodictaskFields
	// periodictaskDescName is the schema descriptor for name field.
	periodictaskDescName := periodictaskFields[1].Descriptor()
	// periodictask.NameValidator is a validator for the "name" field. It is called by the builders before save.
	periodictask.NameValidator = func() func(string) error {
		validators := periodictaskDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// periodictaskDescID is the schema descriptor for id field.
	periodictaskDescID := periodictaskFields[0].Descriptor()
	// periodictask.DefaultID holds the default value on creation for the id field.
	periodictask.DefaultID = periodictaskDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCode is the schema descriptor for code field.
	sessionDescCode := sessionFields[2].Descriptor()
	// session.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	session.CodeValidator = sessionDescCode.Validators[0].(func([]byte) error)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	stashFields := schema.Stash{}.Fields()
	_ = stashFields
	// stashDescContent is the schema descriptor for content field.
	stashDescContent := stashFields[1].Descriptor()
	// stash.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	stash.ContentValidator = stashDescContent.Validators[0].(func([]byte) error)
	// stashDescFileName is the schema descriptor for fileName field.
	stashDescFileName := stashFields[2].Descriptor()
	// stash.FileNameValidator is a validator for the "fileName" field. It is called by the builders before save.
	stash.FileNameValidator = stashDescFileName.Validators[0].(func(string) error)
	// stashDescMime is the schema descriptor for mime field.
	stashDescMime := stashFields[3].Descriptor()
	// stash.MimeValidator is a validator for the "mime" field. It is called by the builders before save.
	stash.MimeValidator = stashDescMime.Validators[0].(func(string) error)
	// stashDescNonce is the schema descriptor for nonce field.
	stashDescNonce := stashFields[4].Descriptor()
	// stash.NonceValidator is a validator for the "nonce" field. It is called by the builders before save.
	stash.NonceValidator = stashDescNonce.Validators[0].(func([]byte) error)
	// stashDescKeySalt is the schema descriptor for keySalt field.
	stashDescKeySalt := stashFields[5].Descriptor()
	// stash.KeySaltValidator is a validator for the "keySalt" field. It is called by the builders before save.
	stash.KeySaltValidator = stashDescKeySalt.Validators[0].(func([]byte) error)
	// stashDescID is the schema descriptor for id field.
	stashDescID := stashFields[0].Descriptor()
	// stash.DefaultID holds the default value on creation for the id field.
	stash.DefaultID = stashDescID.Default.(func() uuid.UUID)
	twofactoractionFields := schema.TwoFactorAction{}.Fields()
	_ = twofactoractionFields
	// twofactoractionDescType is the schema descriptor for type field.
	twofactoractionDescType := twofactoractionFields[1].Descriptor()
	// twofactoraction.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	twofactoraction.TypeValidator = func() func(string) error {
		validators := twofactoractionDescType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_type string) error {
			for _, fn := range fns {
				if err := fn(_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// twofactoractionDescCode is the schema descriptor for code field.
	twofactoractionDescCode := twofactoractionFields[5].Descriptor()
	// twofactoraction.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	twofactoraction.CodeValidator = func() func(string) error {
		validators := twofactoractionDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// twofactoractionDescID is the schema descriptor for id field.
	twofactoractionDescID := twofactoractionFields[0].Descriptor()
	// twofactoraction.DefaultID holds the default value on creation for the id field.
	twofactoraction.DefaultID = twofactoractionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescLocked is the schema descriptor for locked field.
	userDescLocked := userFields[2].Descriptor()
	// user.DefaultLocked holds the default value on creation for the locked field.
	user.DefaultLocked = userDescLocked.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	usermessengerFields := schema.UserMessenger{}.Fields()
	_ = usermessengerFields
	// usermessengerDescType is the schema descriptor for type field.
	usermessengerDescType := usermessengerFields[1].Descriptor()
	// usermessenger.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	usermessenger.TypeValidator = func() func(string) error {
		validators := usermessengerDescType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_type string) error {
			for _, fn := range fns {
				if err := fn(_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// usermessengerDescEnabled is the schema descriptor for enabled field.
	usermessengerDescEnabled := usermessengerFields[3].Descriptor()
	// usermessenger.DefaultEnabled holds the default value on creation for the enabled field.
	usermessenger.DefaultEnabled = usermessengerDescEnabled.Default.(bool)
	// usermessengerDescID is the schema descriptor for id field.
	usermessengerDescID := usermessengerFields[0].Descriptor()
	// usermessenger.DefaultID holds the default value on creation for the id field.
	usermessenger.DefaultID = usermessengerDescID.Default.(func() uuid.UUID)
}
