// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NicoClack/cryptic-stash/backend/ent/predicate"
	"github.com/NicoClack/cryptic-stash/backend/ent/stash"
	"github.com/NicoClack/cryptic-stash/backend/ent/user"
	"github.com/google/uuid"
)

// StashUpdate is the builder for updating Stash entities.
type StashUpdate struct {
	config
	hooks    []Hook
	mutation *StashMutation
}

// Where appends a list predicates to the StashUpdate builder.
func (_u *StashUpdate) Where(ps ...predicate.Stash) *StashUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContent sets the "content" field.
func (_u *StashUpdate) SetContent(v []byte) *StashUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetFileName sets the "fileName" field.
func (_u *StashUpdate) SetFileName(v string) *StashUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "fileName" field if the given value is not nil.
func (_u *StashUpdate) SetNillableFileName(v *string) *StashUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetMime sets the "mime" field.
func (_u *StashUpdate) SetMime(v string) *StashUpdate {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *StashUpdate) SetNillableMime(v *string) *StashUpdate {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *StashUpdate) SetNonce(v []byte) *StashUpdate {
	_u.mutation.SetNonce(v)
	return _u
}

// SetKeySalt sets the "keySalt" field.
func (_u *StashUpdate) SetKeySalt(v []byte) *StashUpdate {
	_u.mutation.SetKeySalt(v)
	return _u
}

// SetHashTime sets the "hashTime" field.
func (_u *StashUpdate) SetHashTime(v uint32) *StashUpdate {
	_u.mutation.ResetHashTime()
	_u.mutation.SetHashTime(v)
	return _u
}

// SetNillableHashTime sets the "hashTime" field if the given value is not nil.
func (_u *StashUpdate) SetNillableHashTime(v *uint32) *StashUpdate {
	if v != nil {
		_u.SetHashTime(*v)
	}
	return _u
}

// AddHashTime adds value to the "hashTime" field.
func (_u *StashUpdate) AddHashTime(v int32) *StashUpdate {
	_u.mutation.AddHashTime(v)
	return _u
}

// SetHashMemory sets the "hashMemory" field.
func (_u *StashUpdate) SetHashMemory(v uint32) *StashUpdate {
	_u.mutation.ResetHashMemory()
	_u.mutation.SetHashMemory(v)
	return _u
}

// SetNillableHashMemory sets the "hashMemory" field if the given value is not nil.
func (_u *StashUpdate) SetNillableHashMemory(v *uint32) *StashUpdate {
	if v != nil {
		_u.SetHashMemory(*v)
	}
	return _u
}

// AddHashMemory adds value to the "hashMemory" field.
func (_u *StashUpdate) AddHashMemory(v int32) *StashUpdate {
	_u.mutation.AddHashMemory(v)
	return _u
}

// SetHashThreads sets the "hashThreads" field.
func (_u *StashUpdate) SetHashThreads(v uint8) *StashUpdate {
	_u.mutation.ResetHashThreads()
	_u.mutation.SetHashThreads(v)
	return _u
}

// SetNillableHashThreads sets the "hashThreads" field if the given value is not nil.
func (_u *StashUpdate) SetNillableHashThreads(v *uint8) *StashUpdate {
	if v != nil {
		_u.SetHashThreads(*v)
	}
	return _u
}

// AddHashThreads adds value to the "hashThreads" field.
func (_u *StashUpdate) AddHashThreads(v int8) *StashUpdate {
	_u.mutation.AddHashThreads(v)
	return _u
}

// SetUserID sets the "userID" field.
func (_u *StashUpdate) SetUserID(v uuid.UUID) *StashUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (_u *StashUpdate) SetNillableUserID(v *uuid.UUID) *StashUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *StashUpdate) SetUser(v *User) *StashUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the StashMutation object of the builder.
func (_u *StashUpdate) Mutation() *StashMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *StashUpdate) ClearUser() *StashUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StashUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StashUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StashUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StashUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StashUpdate) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := stash.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Stash.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := stash.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "fileName", err: fmt.Errorf(`ent: validator failed for field "Stash.fileName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mime(); ok {
		if err := stash.MimeValidator(v); err != nil {
			return &ValidationError{Name: "mime", err: fmt.Errorf(`ent: validator failed for field "Stash.mime": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nonce(); ok {
		if err := stash.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`ent: validator failed for field "Stash.nonce": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeySalt(); ok {
		if err := stash.KeySaltValidator(v); err != nil {
			return &ValidationError{Name: "keySalt", err: fmt.Errorf(`ent: validator failed for field "Stash.keySalt": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Stash.user"`)
	}
	return nil
}

func (_u *StashUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stash.Table, stash.Columns, sqlgraph.NewFieldSpec(stash.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(stash.FieldContent, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(stash.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(stash.FieldMime, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(stash.FieldNonce, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.KeySalt(); ok {
		_spec.SetField(stash.FieldKeySalt, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.HashTime(); ok {
		_spec.SetField(stash.FieldHashTime, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedHashTime(); ok {
		_spec.AddField(stash.FieldHashTime, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.HashMemory(); ok {
		_spec.SetField(stash.FieldHashMemory, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedHashMemory(); ok {
		_spec.AddField(stash.FieldHashMemory, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.HashThreads(); ok {
		_spec.SetField(stash.FieldHashThreads, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedHashThreads(); ok {
		_spec.AddField(stash.FieldHashThreads, field.TypeUint8, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   stash.UserTable,
			Columns: []string{stash.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   stash.UserTable,
			Columns: []string{stash.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stash.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StashUpdateOne is the builder for updating a single Stash entity.
type StashUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StashMutation
}

// SetContent sets the "content" field.
func (_u *StashUpdateOne) SetContent(v []byte) *StashUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetFileName sets the "fileName" field.
func (_u *StashUpdateOne) SetFileName(v string) *StashUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "fileName" field if the given value is not nil.
func (_u *StashUpdateOne) SetNillableFileName(v *string) *StashUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetMime sets the "mime" field.
func (_u *StashUpdateOne) SetMime(v string) *StashUpdateOne {
	_u.mutation.SetMime(v)
	return _u
}

// SetNillableMime sets the "mime" field if the given value is not nil.
func (_u *StashUpdateOne) SetNillableMime(v *string) *StashUpdateOne {
	if v != nil {
		_u.SetMime(*v)
	}
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *StashUpdateOne) SetNonce(v []byte) *StashUpdateOne {
	_u.mutation.SetNonce(v)
	return _u
}

// SetKeySalt sets the "keySalt" field.
func (_u *StashUpdateOne) SetKeySalt(v []byte) *StashUpdateOne {
	_u.mutation.SetKeySalt(v)
	return _u
}

// SetHashTime sets the "hashTime" field.
func (_u *StashUpdateOne) SetHashTime(v uint32) *StashUpdateOne {
	_u.mutation.ResetHashTime()
	_u.mutation.SetHashTime(v)
	return _u
}

// SetNillableHashTime sets the "hashTime" field if the given value is not nil.
func (_u *StashUpdateOne) SetNillableHashTime(v *uint32) *StashUpdateOne {
	if v != nil {
		_u.SetHashTime(*v)
	}
	return _u
}

// AddHashTime adds value to the "hashTime" field.
func (_u *StashUpdateOne) AddHashTime(v int32) *StashUpdateOne {
	_u.mutation.AddHashTime(v)
	return _u
}

// SetHashMemory sets the "hashMemory" field.
func (_u *StashUpdateOne) SetHashMemory(v uint32) *StashUpdateOne {
	_u.mutation.ResetHashMemory()
	_u.mutation.SetHashMemory(v)
	return _u
}

// SetNillableHashMemory sets the "hashMemory" field if the given value is not nil.
func (_u *StashUpdateOne) SetNillableHashMemory(v *uint32) *StashUpdateOne {
	if v != nil {
		_u.SetHashMemory(*v)
	}
	return _u
}

// AddHashMemory adds value to the "hashMemory" field.
func (_u *StashUpdateOne) AddHashMemory(v int32) *StashUpdateOne {
	_u.mutation.AddHashMemory(v)
	return _u
}

// SetHashThreads sets the "hashThreads" field.
func (_u *StashUpdateOne) SetHashThreads(v uint8) *StashUpdateOne {
	_u.mutation.ResetHashThreads()
	_u.mutation.SetHashThreads(v)
	return _u
}

// SetNillableHashThreads sets the "hashThreads" field if the given value is not nil.
func (_u *StashUpdateOne) SetNillableHashThreads(v *uint8) *StashUpdateOne {
	if v != nil {
		_u.SetHashThreads(*v)
	}
	return _u
}

// AddHashThreads adds value to the "hashThreads" field.
func (_u *StashUpdateOne) AddHashThreads(v int8) *StashUpdateOne {
	_u.mutation.AddHashThreads(v)
	return _u
}

// SetUserID sets the "userID" field.
func (_u *StashUpdateOne) SetUserID(v uuid.UUID) *StashUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "userID" field if the given value is not nil.
func (_u *StashUpdateOne) SetNillableUserID(v *uuid.UUID) *StashUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *StashUpdateOne) SetUser(v *User) *StashUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the StashMutation object of the builder.
func (_u *StashUpdateOne) Mutation() *StashMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *StashUpdateOne) ClearUser() *StashUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the StashUpdate builder.
func (_u *StashUpdateOne) Where(ps ...predicate.Stash) *StashUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StashUpdateOne) Select(field string, fields ...string) *StashUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Stash entity.
func (_u *StashUpdateOne) Save(ctx context.Context) (*Stash, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StashUpdateOne) SaveX(ctx context.Context) *Stash {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StashUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StashUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StashUpdateOne) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := stash.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Stash.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := stash.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "fileName", err: fmt.Errorf(`ent: validator failed for field "Stash.fileName": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mime(); ok {
		if err := stash.MimeValidator(v); err != nil {
			return &ValidationError{Name: "mime", err: fmt.Errorf(`ent: validator failed for field "Stash.mime": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nonce(); ok {
		if err := stash.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`ent: validator failed for field "Stash.nonce": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeySalt(); ok {
		if err := stash.KeySaltValidator(v); err != nil {
			return &ValidationError{Name: "keySalt", err: fmt.Errorf(`ent: validator failed for field "Stash.keySalt": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Stash.user"`)
	}
	return nil
}

func (_u *StashUpdateOne) sqlSave(ctx context.Context) (_node *Stash, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stash.Table, stash.Columns, sqlgraph.NewFieldSpec(stash.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Stash.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stash.FieldID)
		for _, f := range fields {
			if !stash.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stash.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(stash.FieldContent, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(stash.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mime(); ok {
		_spec.SetField(stash.FieldMime, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(stash.FieldNonce, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.KeySalt(); ok {
		_spec.SetField(stash.FieldKeySalt, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.HashTime(); ok {
		_spec.SetField(stash.FieldHashTime, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedHashTime(); ok {
		_spec.AddField(stash.FieldHashTime, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.HashMemory(); ok {
		_spec.SetField(stash.FieldHashMemory, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedHashMemory(); ok {
		_spec.AddField(stash.FieldHashMemory, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.HashThreads(); ok {
		_spec.SetField(stash.FieldHashThreads, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedHashThreads(); ok {
		_spec.AddField(stash.FieldHashThreads, field.TypeUint8, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   stash.UserTable,
			Columns: []string{stash.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   stash.UserTable,
			Columns: []string{stash.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Stash{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stash.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
