// Code generated by ent, DO NOT EDIT.

package loginalert

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hedgehog125/project-reboot/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLTE(FieldID, id))
}

// SentAt applies equality check predicate on the "sentAt" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldSentAt, v))
}

// VersionedMessengerType applies equality check predicate on the "versionedMessengerType" field. It's identical to VersionedMessengerTypeEQ.
func VersionedMessengerType(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldVersionedMessengerType, v))
}

// Confirmed applies equality check predicate on the "confirmed" field. It's identical to ConfirmedEQ.
func Confirmed(v bool) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldConfirmed, v))
}

// SessionID applies equality check predicate on the "sessionID" field. It's identical to SessionIDEQ.
func SessionID(v int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldSessionID, v))
}

// SentAtEQ applies the EQ predicate on the "sentAt" field.
func SentAtEQ(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sentAt" field.
func SentAtNEQ(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sentAt" field.
func SentAtIn(vs ...time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sentAt" field.
func SentAtNotIn(vs ...time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sentAt" field.
func SentAtGT(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sentAt" field.
func SentAtGTE(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sentAt" field.
func SentAtLT(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sentAt" field.
func SentAtLTE(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLTE(FieldSentAt, v))
}

// VersionedMessengerTypeEQ applies the EQ predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeEQ(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldVersionedMessengerType, v))
}

// VersionedMessengerTypeNEQ applies the NEQ predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeNEQ(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldVersionedMessengerType, v))
}

// VersionedMessengerTypeIn applies the In predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeIn(vs ...string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldVersionedMessengerType, vs...))
}

// VersionedMessengerTypeNotIn applies the NotIn predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeNotIn(vs ...string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldVersionedMessengerType, vs...))
}

// VersionedMessengerTypeGT applies the GT predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeGT(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGT(FieldVersionedMessengerType, v))
}

// VersionedMessengerTypeGTE applies the GTE predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeGTE(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGTE(FieldVersionedMessengerType, v))
}

// VersionedMessengerTypeLT applies the LT predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeLT(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLT(FieldVersionedMessengerType, v))
}

// VersionedMessengerTypeLTE applies the LTE predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeLTE(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLTE(FieldVersionedMessengerType, v))
}

// VersionedMessengerTypeContains applies the Contains predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeContains(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldContains(FieldVersionedMessengerType, v))
}

// VersionedMessengerTypeHasPrefix applies the HasPrefix predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeHasPrefix(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldHasPrefix(FieldVersionedMessengerType, v))
}

// VersionedMessengerTypeHasSuffix applies the HasSuffix predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeHasSuffix(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldHasSuffix(FieldVersionedMessengerType, v))
}

// VersionedMessengerTypeEqualFold applies the EqualFold predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeEqualFold(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEqualFold(FieldVersionedMessengerType, v))
}

// VersionedMessengerTypeContainsFold applies the ContainsFold predicate on the "versionedMessengerType" field.
func VersionedMessengerTypeContainsFold(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldContainsFold(FieldVersionedMessengerType, v))
}

// ConfirmedEQ applies the EQ predicate on the "confirmed" field.
func ConfirmedEQ(v bool) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldConfirmed, v))
}

// ConfirmedNEQ applies the NEQ predicate on the "confirmed" field.
func ConfirmedNEQ(v bool) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldConfirmed, v))
}

// SessionIDEQ applies the EQ predicate on the "sessionID" field.
func SessionIDEQ(v int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "sessionID" field.
func SessionIDNEQ(v int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "sessionID" field.
func SessionIDIn(vs ...int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "sessionID" field.
func SessionIDNotIn(vs ...int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldSessionID, vs...))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.LoginAlert {
	return predicate.LoginAlert(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.Session) predicate.LoginAlert {
	return predicate.LoginAlert(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LoginAlert) predicate.LoginAlert {
	return predicate.LoginAlert(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LoginAlert) predicate.LoginAlert {
	return predicate.LoginAlert(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LoginAlert) predicate.LoginAlert {
	return predicate.LoginAlert(sql.NotPredicates(p))
}
