// Code generated by ent, DO NOT EDIT.

package loginalert

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hedgehog125/project-reboot/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLTE(FieldID, id))
}

// Time applies equality check predicate on the "time" field. It's identical to TimeEQ.
func Time(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldTime, v))
}

// MessengerType applies equality check predicate on the "messengerType" field. It's identical to MessengerTypeEQ.
func MessengerType(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldMessengerType, v))
}

// Confirmed applies equality check predicate on the "confirmed" field. It's identical to ConfirmedEQ.
func Confirmed(v bool) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldConfirmed, v))
}

// SessionID applies equality check predicate on the "sessionID" field. It's identical to SessionIDEQ.
func SessionID(v int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldSessionID, v))
}

// TimeEQ applies the EQ predicate on the "time" field.
func TimeEQ(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldTime, v))
}

// TimeNEQ applies the NEQ predicate on the "time" field.
func TimeNEQ(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldTime, v))
}

// TimeIn applies the In predicate on the "time" field.
func TimeIn(vs ...time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldTime, vs...))
}

// TimeNotIn applies the NotIn predicate on the "time" field.
func TimeNotIn(vs ...time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldTime, vs...))
}

// TimeGT applies the GT predicate on the "time" field.
func TimeGT(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGT(FieldTime, v))
}

// TimeGTE applies the GTE predicate on the "time" field.
func TimeGTE(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGTE(FieldTime, v))
}

// TimeLT applies the LT predicate on the "time" field.
func TimeLT(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLT(FieldTime, v))
}

// TimeLTE applies the LTE predicate on the "time" field.
func TimeLTE(v time.Time) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLTE(FieldTime, v))
}

// MessengerTypeEQ applies the EQ predicate on the "messengerType" field.
func MessengerTypeEQ(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldMessengerType, v))
}

// MessengerTypeNEQ applies the NEQ predicate on the "messengerType" field.
func MessengerTypeNEQ(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldMessengerType, v))
}

// MessengerTypeIn applies the In predicate on the "messengerType" field.
func MessengerTypeIn(vs ...string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldMessengerType, vs...))
}

// MessengerTypeNotIn applies the NotIn predicate on the "messengerType" field.
func MessengerTypeNotIn(vs ...string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldMessengerType, vs...))
}

// MessengerTypeGT applies the GT predicate on the "messengerType" field.
func MessengerTypeGT(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGT(FieldMessengerType, v))
}

// MessengerTypeGTE applies the GTE predicate on the "messengerType" field.
func MessengerTypeGTE(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldGTE(FieldMessengerType, v))
}

// MessengerTypeLT applies the LT predicate on the "messengerType" field.
func MessengerTypeLT(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLT(FieldMessengerType, v))
}

// MessengerTypeLTE applies the LTE predicate on the "messengerType" field.
func MessengerTypeLTE(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldLTE(FieldMessengerType, v))
}

// MessengerTypeContains applies the Contains predicate on the "messengerType" field.
func MessengerTypeContains(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldContains(FieldMessengerType, v))
}

// MessengerTypeHasPrefix applies the HasPrefix predicate on the "messengerType" field.
func MessengerTypeHasPrefix(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldHasPrefix(FieldMessengerType, v))
}

// MessengerTypeHasSuffix applies the HasSuffix predicate on the "messengerType" field.
func MessengerTypeHasSuffix(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldHasSuffix(FieldMessengerType, v))
}

// MessengerTypeEqualFold applies the EqualFold predicate on the "messengerType" field.
func MessengerTypeEqualFold(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEqualFold(FieldMessengerType, v))
}

// MessengerTypeContainsFold applies the ContainsFold predicate on the "messengerType" field.
func MessengerTypeContainsFold(v string) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldContainsFold(FieldMessengerType, v))
}

// ConfirmedEQ applies the EQ predicate on the "confirmed" field.
func ConfirmedEQ(v bool) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldConfirmed, v))
}

// ConfirmedNEQ applies the NEQ predicate on the "confirmed" field.
func ConfirmedNEQ(v bool) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldConfirmed, v))
}

// SessionIDEQ applies the EQ predicate on the "sessionID" field.
func SessionIDEQ(v int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "sessionID" field.
func SessionIDNEQ(v int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "sessionID" field.
func SessionIDIn(vs ...int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "sessionID" field.
func SessionIDNotIn(vs ...int) predicate.LoginAlert {
	return predicate.LoginAlert(sql.FieldNotIn(FieldSessionID, vs...))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.LoginAlert {
	return predicate.LoginAlert(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.Session) predicate.LoginAlert {
	return predicate.LoginAlert(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LoginAlert) predicate.LoginAlert {
	return predicate.LoginAlert(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LoginAlert) predicate.LoginAlert {
	return predicate.LoginAlert(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LoginAlert) predicate.LoginAlert {
	return predicate.LoginAlert(sql.NotPredicates(p))
}
