// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hedgehog125/project-reboot/ent/loginalert"
	"github.com/hedgehog125/project-reboot/ent/predicate"
	"github.com/hedgehog125/project-reboot/ent/session"
)

// LoginAlertUpdate is the builder for updating LoginAlert entities.
type LoginAlertUpdate struct {
	config
	hooks    []Hook
	mutation *LoginAlertMutation
}

// Where appends a list predicates to the LoginAlertUpdate builder.
func (_u *LoginAlertUpdate) Where(ps ...predicate.LoginAlert) *LoginAlertUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTime sets the "time" field.
func (_u *LoginAlertUpdate) SetTime(v time.Time) *LoginAlertUpdate {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *LoginAlertUpdate) SetNillableTime(v *time.Time) *LoginAlertUpdate {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetVersionedMessengerType sets the "versionedMessengerType" field.
func (_u *LoginAlertUpdate) SetVersionedMessengerType(v string) *LoginAlertUpdate {
	_u.mutation.SetVersionedMessengerType(v)
	return _u
}

// SetNillableVersionedMessengerType sets the "versionedMessengerType" field if the given value is not nil.
func (_u *LoginAlertUpdate) SetNillableVersionedMessengerType(v *string) *LoginAlertUpdate {
	if v != nil {
		_u.SetVersionedMessengerType(*v)
	}
	return _u
}

// SetConfirmed sets the "confirmed" field.
func (_u *LoginAlertUpdate) SetConfirmed(v bool) *LoginAlertUpdate {
	_u.mutation.SetConfirmed(v)
	return _u
}

// SetNillableConfirmed sets the "confirmed" field if the given value is not nil.
func (_u *LoginAlertUpdate) SetNillableConfirmed(v *bool) *LoginAlertUpdate {
	if v != nil {
		_u.SetConfirmed(*v)
	}
	return _u
}

// SetSessionID sets the "sessionID" field.
func (_u *LoginAlertUpdate) SetSessionID(v int) *LoginAlertUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "sessionID" field if the given value is not nil.
func (_u *LoginAlertUpdate) SetNillableSessionID(v *int) *LoginAlertUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *LoginAlertUpdate) SetSession(v *Session) *LoginAlertUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the LoginAlertMutation object of the builder.
func (_u *LoginAlertUpdate) Mutation() *LoginAlertMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *LoginAlertUpdate) ClearSession() *LoginAlertUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoginAlertUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginAlertUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoginAlertUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginAlertUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginAlertUpdate) check() error {
	if v, ok := _u.mutation.VersionedMessengerType(); ok {
		if err := loginalert.VersionedMessengerTypeValidator(v); err != nil {
			return &ValidationError{Name: "versionedMessengerType", err: fmt.Errorf(`ent: validator failed for field "LoginAlert.versionedMessengerType": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LoginAlert.session"`)
	}
	return nil
}

func (_u *LoginAlertUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginalert.Table, loginalert.Columns, sqlgraph.NewFieldSpec(loginalert.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(loginalert.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VersionedMessengerType(); ok {
		_spec.SetField(loginalert.FieldVersionedMessengerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confirmed(); ok {
		_spec.SetField(loginalert.FieldConfirmed, field.TypeBool, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loginalert.SessionTable,
			Columns: []string{loginalert.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loginalert.SessionTable,
			Columns: []string{loginalert.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginalert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoginAlertUpdateOne is the builder for updating a single LoginAlert entity.
type LoginAlertUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoginAlertMutation
}

// SetTime sets the "time" field.
func (_u *LoginAlertUpdateOne) SetTime(v time.Time) *LoginAlertUpdateOne {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *LoginAlertUpdateOne) SetNillableTime(v *time.Time) *LoginAlertUpdateOne {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetVersionedMessengerType sets the "versionedMessengerType" field.
func (_u *LoginAlertUpdateOne) SetVersionedMessengerType(v string) *LoginAlertUpdateOne {
	_u.mutation.SetVersionedMessengerType(v)
	return _u
}

// SetNillableVersionedMessengerType sets the "versionedMessengerType" field if the given value is not nil.
func (_u *LoginAlertUpdateOne) SetNillableVersionedMessengerType(v *string) *LoginAlertUpdateOne {
	if v != nil {
		_u.SetVersionedMessengerType(*v)
	}
	return _u
}

// SetConfirmed sets the "confirmed" field.
func (_u *LoginAlertUpdateOne) SetConfirmed(v bool) *LoginAlertUpdateOne {
	_u.mutation.SetConfirmed(v)
	return _u
}

// SetNillableConfirmed sets the "confirmed" field if the given value is not nil.
func (_u *LoginAlertUpdateOne) SetNillableConfirmed(v *bool) *LoginAlertUpdateOne {
	if v != nil {
		_u.SetConfirmed(*v)
	}
	return _u
}

// SetSessionID sets the "sessionID" field.
func (_u *LoginAlertUpdateOne) SetSessionID(v int) *LoginAlertUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "sessionID" field if the given value is not nil.
func (_u *LoginAlertUpdateOne) SetNillableSessionID(v *int) *LoginAlertUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *LoginAlertUpdateOne) SetSession(v *Session) *LoginAlertUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the LoginAlertMutation object of the builder.
func (_u *LoginAlertUpdateOne) Mutation() *LoginAlertMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *LoginAlertUpdateOne) ClearSession() *LoginAlertUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the LoginAlertUpdate builder.
func (_u *LoginAlertUpdateOne) Where(ps ...predicate.LoginAlert) *LoginAlertUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoginAlertUpdateOne) Select(field string, fields ...string) *LoginAlertUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LoginAlert entity.
func (_u *LoginAlertUpdateOne) Save(ctx context.Context) (*LoginAlert, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginAlertUpdateOne) SaveX(ctx context.Context) *LoginAlert {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoginAlertUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginAlertUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginAlertUpdateOne) check() error {
	if v, ok := _u.mutation.VersionedMessengerType(); ok {
		if err := loginalert.VersionedMessengerTypeValidator(v); err != nil {
			return &ValidationError{Name: "versionedMessengerType", err: fmt.Errorf(`ent: validator failed for field "LoginAlert.versionedMessengerType": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LoginAlert.session"`)
	}
	return nil
}

func (_u *LoginAlertUpdateOne) sqlSave(ctx context.Context) (_node *LoginAlert, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginalert.Table, loginalert.Columns, sqlgraph.NewFieldSpec(loginalert.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LoginAlert.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginalert.FieldID)
		for _, f := range fields {
			if !loginalert.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loginalert.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(loginalert.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VersionedMessengerType(); ok {
		_spec.SetField(loginalert.FieldVersionedMessengerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confirmed(); ok {
		_spec.SetField(loginalert.FieldConfirmed, field.TypeBool, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loginalert.SessionTable,
			Columns: []string{loginalert.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loginalert.SessionTable,
			Columns: []string{loginalert.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LoginAlert{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginalert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
