// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hedgehog125/project-reboot/ent/loginalerts"
	"github.com/hedgehog125/project-reboot/ent/predicate"
	"github.com/hedgehog125/project-reboot/ent/session"
)

// LoginAlertsUpdate is the builder for updating LoginAlerts entities.
type LoginAlertsUpdate struct {
	config
	hooks    []Hook
	mutation *LoginAlertsMutation
}

// Where appends a list predicates to the LoginAlertsUpdate builder.
func (_u *LoginAlertsUpdate) Where(ps ...predicate.LoginAlerts) *LoginAlertsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTime sets the "time" field.
func (_u *LoginAlertsUpdate) SetTime(v time.Time) *LoginAlertsUpdate {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *LoginAlertsUpdate) SetNillableTime(v *time.Time) *LoginAlertsUpdate {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetMessengerType sets the "messengerType" field.
func (_u *LoginAlertsUpdate) SetMessengerType(v string) *LoginAlertsUpdate {
	_u.mutation.SetMessengerType(v)
	return _u
}

// SetNillableMessengerType sets the "messengerType" field if the given value is not nil.
func (_u *LoginAlertsUpdate) SetNillableMessengerType(v *string) *LoginAlertsUpdate {
	if v != nil {
		_u.SetMessengerType(*v)
	}
	return _u
}

// SetConfirmed sets the "confirmed" field.
func (_u *LoginAlertsUpdate) SetConfirmed(v bool) *LoginAlertsUpdate {
	_u.mutation.SetConfirmed(v)
	return _u
}

// SetNillableConfirmed sets the "confirmed" field if the given value is not nil.
func (_u *LoginAlertsUpdate) SetNillableConfirmed(v *bool) *LoginAlertsUpdate {
	if v != nil {
		_u.SetConfirmed(*v)
	}
	return _u
}

// SetSessionID sets the "sessionID" field.
func (_u *LoginAlertsUpdate) SetSessionID(v int) *LoginAlertsUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "sessionID" field if the given value is not nil.
func (_u *LoginAlertsUpdate) SetNillableSessionID(v *int) *LoginAlertsUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *LoginAlertsUpdate) SetSession(v *Session) *LoginAlertsUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the LoginAlertsMutation object of the builder.
func (_u *LoginAlertsUpdate) Mutation() *LoginAlertsMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *LoginAlertsUpdate) ClearSession() *LoginAlertsUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoginAlertsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginAlertsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoginAlertsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginAlertsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginAlertsUpdate) check() error {
	if v, ok := _u.mutation.MessengerType(); ok {
		if err := loginalerts.MessengerTypeValidator(v); err != nil {
			return &ValidationError{Name: "messengerType", err: fmt.Errorf(`ent: validator failed for field "LoginAlerts.messengerType": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LoginAlerts.session"`)
	}
	return nil
}

func (_u *LoginAlertsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginalerts.Table, loginalerts.Columns, sqlgraph.NewFieldSpec(loginalerts.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(loginalerts.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MessengerType(); ok {
		_spec.SetField(loginalerts.FieldMessengerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confirmed(); ok {
		_spec.SetField(loginalerts.FieldConfirmed, field.TypeBool, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loginalerts.SessionTable,
			Columns: []string{loginalerts.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loginalerts.SessionTable,
			Columns: []string{loginalerts.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginalerts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoginAlertsUpdateOne is the builder for updating a single LoginAlerts entity.
type LoginAlertsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoginAlertsMutation
}

// SetTime sets the "time" field.
func (_u *LoginAlertsUpdateOne) SetTime(v time.Time) *LoginAlertsUpdateOne {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *LoginAlertsUpdateOne) SetNillableTime(v *time.Time) *LoginAlertsUpdateOne {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetMessengerType sets the "messengerType" field.
func (_u *LoginAlertsUpdateOne) SetMessengerType(v string) *LoginAlertsUpdateOne {
	_u.mutation.SetMessengerType(v)
	return _u
}

// SetNillableMessengerType sets the "messengerType" field if the given value is not nil.
func (_u *LoginAlertsUpdateOne) SetNillableMessengerType(v *string) *LoginAlertsUpdateOne {
	if v != nil {
		_u.SetMessengerType(*v)
	}
	return _u
}

// SetConfirmed sets the "confirmed" field.
func (_u *LoginAlertsUpdateOne) SetConfirmed(v bool) *LoginAlertsUpdateOne {
	_u.mutation.SetConfirmed(v)
	return _u
}

// SetNillableConfirmed sets the "confirmed" field if the given value is not nil.
func (_u *LoginAlertsUpdateOne) SetNillableConfirmed(v *bool) *LoginAlertsUpdateOne {
	if v != nil {
		_u.SetConfirmed(*v)
	}
	return _u
}

// SetSessionID sets the "sessionID" field.
func (_u *LoginAlertsUpdateOne) SetSessionID(v int) *LoginAlertsUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "sessionID" field if the given value is not nil.
func (_u *LoginAlertsUpdateOne) SetNillableSessionID(v *int) *LoginAlertsUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *LoginAlertsUpdateOne) SetSession(v *Session) *LoginAlertsUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the LoginAlertsMutation object of the builder.
func (_u *LoginAlertsUpdateOne) Mutation() *LoginAlertsMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *LoginAlertsUpdateOne) ClearSession() *LoginAlertsUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the LoginAlertsUpdate builder.
func (_u *LoginAlertsUpdateOne) Where(ps ...predicate.LoginAlerts) *LoginAlertsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoginAlertsUpdateOne) Select(field string, fields ...string) *LoginAlertsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LoginAlerts entity.
func (_u *LoginAlertsUpdateOne) Save(ctx context.Context) (*LoginAlerts, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginAlertsUpdateOne) SaveX(ctx context.Context) *LoginAlerts {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoginAlertsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginAlertsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginAlertsUpdateOne) check() error {
	if v, ok := _u.mutation.MessengerType(); ok {
		if err := loginalerts.MessengerTypeValidator(v); err != nil {
			return &ValidationError{Name: "messengerType", err: fmt.Errorf(`ent: validator failed for field "LoginAlerts.messengerType": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LoginAlerts.session"`)
	}
	return nil
}

func (_u *LoginAlertsUpdateOne) sqlSave(ctx context.Context) (_node *LoginAlerts, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginalerts.Table, loginalerts.Columns, sqlgraph.NewFieldSpec(loginalerts.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LoginAlerts.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginalerts.FieldID)
		for _, f := range fields {
			if !loginalerts.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loginalerts.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(loginalerts.FieldTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MessengerType(); ok {
		_spec.SetField(loginalerts.FieldMessengerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confirmed(); ok {
		_spec.SetField(loginalerts.FieldConfirmed, field.TypeBool, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loginalerts.SessionTable,
			Columns: []string{loginalerts.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loginalerts.SessionTable,
			Columns: []string{loginalerts.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LoginAlerts{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginalerts.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
