// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hedgehog125/project-reboot/ent/periodicjob"
)

// PeriodicJob is the model entity for the PeriodicJob schema.
type PeriodicJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// LastScheduledNewJob holds the value of the "lastScheduledNewJob" field.
	LastScheduledNewJob time.Time `json:"lastScheduledNewJob,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PeriodicJobQuery when eager-loading is set.
	Edges        PeriodicJobEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PeriodicJobEdges holds the relations/edges for other nodes in the graph.
type PeriodicJobEdges struct {
	// Jobs holds the value of the jobs edge.
	Jobs []*Job `json:"jobs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// JobsOrErr returns the Jobs value or an error if the edge
// was not loaded in eager-loading.
func (e PeriodicJobEdges) JobsOrErr() ([]*Job, error) {
	if e.loadedTypes[0] {
		return e.Jobs, nil
	}
	return nil, &NotLoadedError{edge: "jobs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PeriodicJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case periodicjob.FieldID, periodicjob.FieldVersion:
			values[i] = new(sql.NullInt64)
		case periodicjob.FieldType:
			values[i] = new(sql.NullString)
		case periodicjob.FieldLastScheduledNewJob:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PeriodicJob fields.
func (_m *PeriodicJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case periodicjob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case periodicjob.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case periodicjob.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case periodicjob.FieldLastScheduledNewJob:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lastScheduledNewJob", values[i])
			} else if value.Valid {
				_m.LastScheduledNewJob = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PeriodicJob.
// This includes values selected through modifiers, order, etc.
func (_m *PeriodicJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryJobs queries the "jobs" edge of the PeriodicJob entity.
func (_m *PeriodicJob) QueryJobs() *JobQuery {
	return NewPeriodicJobClient(_m.config).QueryJobs(_m)
}

// Update returns a builder for updating this PeriodicJob.
// Note that you need to call PeriodicJob.Unwrap() before calling this method if this PeriodicJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PeriodicJob) Update() *PeriodicJobUpdateOne {
	return NewPeriodicJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PeriodicJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PeriodicJob) Unwrap() *PeriodicJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PeriodicJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PeriodicJob) String() string {
	var builder strings.Builder
	builder.WriteString("PeriodicJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("lastScheduledNewJob=")
	builder.WriteString(_m.LastScheduledNewJob.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PeriodicJobs is a parsable slice of PeriodicJob.
type PeriodicJobs []*PeriodicJob
