// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/hedgehog125/project-reboot/ent/job"
	"github.com/hedgehog125/project-reboot/ent/periodicjob"
	"github.com/hedgehog125/project-reboot/ent/predicate"
)

// PeriodicJobUpdate is the builder for updating PeriodicJob entities.
type PeriodicJobUpdate struct {
	config
	hooks    []Hook
	mutation *PeriodicJobMutation
}

// Where appends a list predicates to the PeriodicJobUpdate builder.
func (_u *PeriodicJobUpdate) Where(ps ...predicate.PeriodicJob) *PeriodicJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *PeriodicJobUpdate) SetType(v string) *PeriodicJobUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PeriodicJobUpdate) SetNillableType(v *string) *PeriodicJobUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PeriodicJobUpdate) SetVersion(v int) *PeriodicJobUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PeriodicJobUpdate) SetNillableVersion(v *int) *PeriodicJobUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PeriodicJobUpdate) AddVersion(v int) *PeriodicJobUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetLastScheduledNewJob sets the "lastScheduledNewJob" field.
func (_u *PeriodicJobUpdate) SetLastScheduledNewJob(v time.Time) *PeriodicJobUpdate {
	_u.mutation.SetLastScheduledNewJob(v)
	return _u
}

// SetNillableLastScheduledNewJob sets the "lastScheduledNewJob" field if the given value is not nil.
func (_u *PeriodicJobUpdate) SetNillableLastScheduledNewJob(v *time.Time) *PeriodicJobUpdate {
	if v != nil {
		_u.SetLastScheduledNewJob(*v)
	}
	return _u
}

// ClearLastScheduledNewJob clears the value of the "lastScheduledNewJob" field.
func (_u *PeriodicJobUpdate) ClearLastScheduledNewJob() *PeriodicJobUpdate {
	_u.mutation.ClearLastScheduledNewJob()
	return _u
}

// AddJobIDs adds the "jobs" edge to the Job entity by IDs.
func (_u *PeriodicJobUpdate) AddJobIDs(ids ...uuid.UUID) *PeriodicJobUpdate {
	_u.mutation.AddJobIDs(ids...)
	return _u
}

// AddJobs adds the "jobs" edges to the Job entity.
func (_u *PeriodicJobUpdate) AddJobs(v ...*Job) *PeriodicJobUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobIDs(ids...)
}

// Mutation returns the PeriodicJobMutation object of the builder.
func (_u *PeriodicJobUpdate) Mutation() *PeriodicJobMutation {
	return _u.mutation
}

// ClearJobs clears all "jobs" edges to the Job entity.
func (_u *PeriodicJobUpdate) ClearJobs() *PeriodicJobUpdate {
	_u.mutation.ClearJobs()
	return _u
}

// RemoveJobIDs removes the "jobs" edge to Job entities by IDs.
func (_u *PeriodicJobUpdate) RemoveJobIDs(ids ...uuid.UUID) *PeriodicJobUpdate {
	_u.mutation.RemoveJobIDs(ids...)
	return _u
}

// RemoveJobs removes "jobs" edges to Job entities.
func (_u *PeriodicJobUpdate) RemoveJobs(v ...*Job) *PeriodicJobUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PeriodicJobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PeriodicJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PeriodicJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PeriodicJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PeriodicJobUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := periodicjob.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "PeriodicJob.type": %w`, err)}
		}
	}
	return nil
}

func (_u *PeriodicJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(periodicjob.Table, periodicjob.Columns, sqlgraph.NewFieldSpec(periodicjob.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(periodicjob.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(periodicjob.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(periodicjob.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastScheduledNewJob(); ok {
		_spec.SetField(periodicjob.FieldLastScheduledNewJob, field.TypeTime, value)
	}
	if _u.mutation.LastScheduledNewJobCleared() {
		_spec.ClearField(periodicjob.FieldLastScheduledNewJob, field.TypeTime)
	}
	if _u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   periodicjob.JobsTable,
			Columns: []string{periodicjob.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobsIDs(); len(nodes) > 0 && !_u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   periodicjob.JobsTable,
			Columns: []string{periodicjob.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   periodicjob.JobsTable,
			Columns: []string{periodicjob.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{periodicjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PeriodicJobUpdateOne is the builder for updating a single PeriodicJob entity.
type PeriodicJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PeriodicJobMutation
}

// SetType sets the "type" field.
func (_u *PeriodicJobUpdateOne) SetType(v string) *PeriodicJobUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PeriodicJobUpdateOne) SetNillableType(v *string) *PeriodicJobUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PeriodicJobUpdateOne) SetVersion(v int) *PeriodicJobUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PeriodicJobUpdateOne) SetNillableVersion(v *int) *PeriodicJobUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PeriodicJobUpdateOne) AddVersion(v int) *PeriodicJobUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetLastScheduledNewJob sets the "lastScheduledNewJob" field.
func (_u *PeriodicJobUpdateOne) SetLastScheduledNewJob(v time.Time) *PeriodicJobUpdateOne {
	_u.mutation.SetLastScheduledNewJob(v)
	return _u
}

// SetNillableLastScheduledNewJob sets the "lastScheduledNewJob" field if the given value is not nil.
func (_u *PeriodicJobUpdateOne) SetNillableLastScheduledNewJob(v *time.Time) *PeriodicJobUpdateOne {
	if v != nil {
		_u.SetLastScheduledNewJob(*v)
	}
	return _u
}

// ClearLastScheduledNewJob clears the value of the "lastScheduledNewJob" field.
func (_u *PeriodicJobUpdateOne) ClearLastScheduledNewJob() *PeriodicJobUpdateOne {
	_u.mutation.ClearLastScheduledNewJob()
	return _u
}

// AddJobIDs adds the "jobs" edge to the Job entity by IDs.
func (_u *PeriodicJobUpdateOne) AddJobIDs(ids ...uuid.UUID) *PeriodicJobUpdateOne {
	_u.mutation.AddJobIDs(ids...)
	return _u
}

// AddJobs adds the "jobs" edges to the Job entity.
func (_u *PeriodicJobUpdateOne) AddJobs(v ...*Job) *PeriodicJobUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJobIDs(ids...)
}

// Mutation returns the PeriodicJobMutation object of the builder.
func (_u *PeriodicJobUpdateOne) Mutation() *PeriodicJobMutation {
	return _u.mutation
}

// ClearJobs clears all "jobs" edges to the Job entity.
func (_u *PeriodicJobUpdateOne) ClearJobs() *PeriodicJobUpdateOne {
	_u.mutation.ClearJobs()
	return _u
}

// RemoveJobIDs removes the "jobs" edge to Job entities by IDs.
func (_u *PeriodicJobUpdateOne) RemoveJobIDs(ids ...uuid.UUID) *PeriodicJobUpdateOne {
	_u.mutation.RemoveJobIDs(ids...)
	return _u
}

// RemoveJobs removes "jobs" edges to Job entities.
func (_u *PeriodicJobUpdateOne) RemoveJobs(v ...*Job) *PeriodicJobUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJobIDs(ids...)
}

// Where appends a list predicates to the PeriodicJobUpdate builder.
func (_u *PeriodicJobUpdateOne) Where(ps ...predicate.PeriodicJob) *PeriodicJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PeriodicJobUpdateOne) Select(field string, fields ...string) *PeriodicJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PeriodicJob entity.
func (_u *PeriodicJobUpdateOne) Save(ctx context.Context) (*PeriodicJob, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PeriodicJobUpdateOne) SaveX(ctx context.Context) *PeriodicJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PeriodicJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PeriodicJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PeriodicJobUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := periodicjob.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "PeriodicJob.type": %w`, err)}
		}
	}
	return nil
}

func (_u *PeriodicJobUpdateOne) sqlSave(ctx context.Context) (_node *PeriodicJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(periodicjob.Table, periodicjob.Columns, sqlgraph.NewFieldSpec(periodicjob.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PeriodicJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, periodicjob.FieldID)
		for _, f := range fields {
			if !periodicjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != periodicjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(periodicjob.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(periodicjob.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(periodicjob.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastScheduledNewJob(); ok {
		_spec.SetField(periodicjob.FieldLastScheduledNewJob, field.TypeTime, value)
	}
	if _u.mutation.LastScheduledNewJobCleared() {
		_spec.ClearField(periodicjob.FieldLastScheduledNewJob, field.TypeTime)
	}
	if _u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   periodicjob.JobsTable,
			Columns: []string{periodicjob.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJobsIDs(); len(nodes) > 0 && !_u.mutation.JobsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   periodicjob.JobsTable,
			Columns: []string{periodicjob.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   periodicjob.JobsTable,
			Columns: []string{periodicjob.JobsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PeriodicJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{periodicjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
