// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hedgehog125/project-reboot/ent/loginalert"
	"github.com/hedgehog125/project-reboot/ent/session"
	"github.com/hedgehog125/project-reboot/ent/user"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTime sets the "time" field.
func (_c *SessionCreate) SetTime(v time.Time) *SessionCreate {
	_c.mutation.SetTime(v)
	return _c
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_c *SessionCreate) SetNillableTime(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetTime(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *SessionCreate) SetCode(v []byte) *SessionCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetValidFrom sets the "validFrom" field.
func (_c *SessionCreate) SetValidFrom(v time.Time) *SessionCreate {
	_c.mutation.SetValidFrom(v)
	return _c
}

// SetValidUntil sets the "validUntil" field.
func (_c *SessionCreate) SetValidUntil(v time.Time) *SessionCreate {
	_c.mutation.SetValidUntil(v)
	return _c
}

// SetUserAgent sets the "userAgent" field.
func (_c *SessionCreate) SetUserAgent(v string) *SessionCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *SessionCreate) SetIP(v string) *SessionCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetUserID sets the "userID" field.
func (_c *SessionCreate) SetUserID(v int) *SessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SessionCreate) SetUser(v *User) *SessionCreate {
	return _c.SetUserID(v.ID)
}

// AddLoginAlertIDs adds the "loginAlerts" edge to the LoginAlert entity by IDs.
func (_c *SessionCreate) AddLoginAlertIDs(ids ...int) *SessionCreate {
	_c.mutation.AddLoginAlertIDs(ids...)
	return _c
}

// AddLoginAlerts adds the "loginAlerts" edges to the LoginAlert entity.
func (_c *SessionCreate) AddLoginAlerts(v ...*LoginAlert) *SessionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLoginAlertIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_c *SessionCreate) Mutation() *SessionMutation {
	return _c.mutation
}

// Save creates the Session in the database.
func (_c *SessionCreate) Save(ctx context.Context) (*Session, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SessionCreate) defaults() {
	if _, ok := _c.mutation.Time(); !ok {
		v := session.DefaultTime()
		_c.mutation.SetTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionCreate) check() error {
	if _, ok := _c.mutation.Time(); !ok {
		return &ValidationError{Name: "time", err: errors.New(`ent: missing required field "Session.time"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Session.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := session.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Session.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidFrom(); !ok {
		return &ValidationError{Name: "validFrom", err: errors.New(`ent: missing required field "Session.validFrom"`)}
	}
	if _, ok := _c.mutation.ValidUntil(); !ok {
		return &ValidationError{Name: "validUntil", err: errors.New(`ent: missing required field "Session.validUntil"`)}
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "userAgent", err: errors.New(`ent: missing required field "Session.userAgent"`)}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Session.ip"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "userID", err: errors.New(`ent: missing required field "Session.userID"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Session.user"`)}
	}
	return nil
}

func (_c *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionCreate) createSpec() (*Session, *sqlgraph.CreateSpec) {
	var (
		_node = &Session{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(session.Table, sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Time(); ok {
		_spec.SetField(session.FieldTime, field.TypeTime, value)
		_node.Time = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(session.FieldCode, field.TypeBytes, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.ValidFrom(); ok {
		_spec.SetField(session.FieldValidFrom, field.TypeTime, value)
		_node.ValidFrom = value
	}
	if value, ok := _c.mutation.ValidUntil(); ok {
		_spec.SetField(session.FieldValidUntil, field.TypeTime, value)
		_node.ValidUntil = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(session.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LoginAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.LoginAlertsTable,
			Columns: []string{session.LoginAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loginalert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Session.Create().
//		SetTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SessionUpsert) {
//			SetTime(v+v).
//		}).
//		Exec(ctx)
func (_c *SessionCreate) OnConflict(opts ...sql.ConflictOption) *SessionUpsertOne {
	_c.conflict = opts
	return &SessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Session.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SessionCreate) OnConflictColumns(columns ...string) *SessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SessionUpsertOne{
		create: _c,
	}
}

type (
	// SessionUpsertOne is the builder for "upsert"-ing
	//  one Session node.
	SessionUpsertOne struct {
		create *SessionCreate
	}

	// SessionUpsert is the "OnConflict" setter.
	SessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetTime sets the "time" field.
func (u *SessionUpsert) SetTime(v time.Time) *SessionUpsert {
	u.Set(session.FieldTime, v)
	return u
}

// UpdateTime sets the "time" field to the value that was provided on create.
func (u *SessionUpsert) UpdateTime() *SessionUpsert {
	u.SetExcluded(session.FieldTime)
	return u
}

// SetCode sets the "code" field.
func (u *SessionUpsert) SetCode(v []byte) *SessionUpsert {
	u.Set(session.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SessionUpsert) UpdateCode() *SessionUpsert {
	u.SetExcluded(session.FieldCode)
	return u
}

// SetValidFrom sets the "validFrom" field.
func (u *SessionUpsert) SetValidFrom(v time.Time) *SessionUpsert {
	u.Set(session.FieldValidFrom, v)
	return u
}

// UpdateValidFrom sets the "validFrom" field to the value that was provided on create.
func (u *SessionUpsert) UpdateValidFrom() *SessionUpsert {
	u.SetExcluded(session.FieldValidFrom)
	return u
}

// SetValidUntil sets the "validUntil" field.
func (u *SessionUpsert) SetValidUntil(v time.Time) *SessionUpsert {
	u.Set(session.FieldValidUntil, v)
	return u
}

// UpdateValidUntil sets the "validUntil" field to the value that was provided on create.
func (u *SessionUpsert) UpdateValidUntil() *SessionUpsert {
	u.SetExcluded(session.FieldValidUntil)
	return u
}

// SetUserAgent sets the "userAgent" field.
func (u *SessionUpsert) SetUserAgent(v string) *SessionUpsert {
	u.Set(session.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "userAgent" field to the value that was provided on create.
func (u *SessionUpsert) UpdateUserAgent() *SessionUpsert {
	u.SetExcluded(session.FieldUserAgent)
	return u
}

// SetIP sets the "ip" field.
func (u *SessionUpsert) SetIP(v string) *SessionUpsert {
	u.Set(session.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *SessionUpsert) UpdateIP() *SessionUpsert {
	u.SetExcluded(session.FieldIP)
	return u
}

// SetUserID sets the "userID" field.
func (u *SessionUpsert) SetUserID(v int) *SessionUpsert {
	u.Set(session.FieldUserID, v)
	return u
}

// UpdateUserID sets the "userID" field to the value that was provided on create.
func (u *SessionUpsert) UpdateUserID() *SessionUpsert {
	u.SetExcluded(session.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Session.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SessionUpsertOne) UpdateNewValues() *SessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Session.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SessionUpsertOne) Ignore() *SessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SessionUpsertOne) DoNothing() *SessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SessionCreate.OnConflict
// documentation for more info.
func (u *SessionUpsertOne) Update(set func(*SessionUpsert)) *SessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTime sets the "time" field.
func (u *SessionUpsertOne) SetTime(v time.Time) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetTime(v)
	})
}

// UpdateTime sets the "time" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateTime() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateTime()
	})
}

// SetCode sets the "code" field.
func (u *SessionUpsertOne) SetCode(v []byte) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateCode() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateCode()
	})
}

// SetValidFrom sets the "validFrom" field.
func (u *SessionUpsertOne) SetValidFrom(v time.Time) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetValidFrom(v)
	})
}

// UpdateValidFrom sets the "validFrom" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateValidFrom() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateValidFrom()
	})
}

// SetValidUntil sets the "validUntil" field.
func (u *SessionUpsertOne) SetValidUntil(v time.Time) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetValidUntil(v)
	})
}

// UpdateValidUntil sets the "validUntil" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateValidUntil() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateValidUntil()
	})
}

// SetUserAgent sets the "userAgent" field.
func (u *SessionUpsertOne) SetUserAgent(v string) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "userAgent" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateUserAgent() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateUserAgent()
	})
}

// SetIP sets the "ip" field.
func (u *SessionUpsertOne) SetIP(v string) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateIP() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateIP()
	})
}

// SetUserID sets the "userID" field.
func (u *SessionUpsertOne) SetUserID(v int) *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "userID" field to the value that was provided on create.
func (u *SessionUpsertOne) UpdateUserID() *SessionUpsertOne {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *SessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SessionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SessionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SessionCreateBulk is the builder for creating many Session entities in bulk.
type SessionCreateBulk struct {
	config
	err      error
	builders []*SessionCreate
	conflict []sql.ConflictOption
}

// Save creates the Session entities in the database.
func (_c *SessionCreateBulk) Save(ctx context.Context) ([]*Session, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Session, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionCreateBulk) SaveX(ctx context.Context) []*Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Session.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SessionUpsert) {
//			SetTime(v+v).
//		}).
//		Exec(ctx)
func (_c *SessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SessionUpsertBulk {
	_c.conflict = opts
	return &SessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Session.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SessionCreateBulk) OnConflictColumns(columns ...string) *SessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SessionUpsertBulk{
		create: _c,
	}
}

// SessionUpsertBulk is the builder for "upsert"-ing
// a bulk of Session nodes.
type SessionUpsertBulk struct {
	create *SessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Session.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SessionUpsertBulk) UpdateNewValues() *SessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Session.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SessionUpsertBulk) Ignore() *SessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SessionUpsertBulk) DoNothing() *SessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SessionCreateBulk.OnConflict
// documentation for more info.
func (u *SessionUpsertBulk) Update(set func(*SessionUpsert)) *SessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTime sets the "time" field.
func (u *SessionUpsertBulk) SetTime(v time.Time) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetTime(v)
	})
}

// UpdateTime sets the "time" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateTime() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateTime()
	})
}

// SetCode sets the "code" field.
func (u *SessionUpsertBulk) SetCode(v []byte) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateCode() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateCode()
	})
}

// SetValidFrom sets the "validFrom" field.
func (u *SessionUpsertBulk) SetValidFrom(v time.Time) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetValidFrom(v)
	})
}

// UpdateValidFrom sets the "validFrom" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateValidFrom() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateValidFrom()
	})
}

// SetValidUntil sets the "validUntil" field.
func (u *SessionUpsertBulk) SetValidUntil(v time.Time) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetValidUntil(v)
	})
}

// UpdateValidUntil sets the "validUntil" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateValidUntil() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateValidUntil()
	})
}

// SetUserAgent sets the "userAgent" field.
func (u *SessionUpsertBulk) SetUserAgent(v string) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "userAgent" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateUserAgent() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateUserAgent()
	})
}

// SetIP sets the "ip" field.
func (u *SessionUpsertBulk) SetIP(v string) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateIP() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateIP()
	})
}

// SetUserID sets the "userID" field.
func (u *SessionUpsertBulk) SetUserID(v int) *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "userID" field to the value that was provided on create.
func (u *SessionUpsertBulk) UpdateUserID() *SessionUpsertBulk {
	return u.Update(func(s *SessionUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *SessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
