// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/hedgehog125/project-reboot/ent/twofactoraction"
)

// TwoFactorAction is the model entity for the TwoFactorAction schema.
type TwoFactorAction struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// Data holds the value of the "data" field.
	Data *map[string]interface{} `json:"data,omitempty"`
	// ExpiresAt holds the value of the "expiresAt" field.
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
	// Code holds the value of the "code" field.
	Code         string `json:"code,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TwoFactorAction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case twofactoraction.FieldData:
			values[i] = new([]byte)
		case twofactoraction.FieldID, twofactoraction.FieldVersion:
			values[i] = new(sql.NullInt64)
		case twofactoraction.FieldType, twofactoraction.FieldCode:
			values[i] = new(sql.NullString)
		case twofactoraction.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TwoFactorAction fields.
func (tfa *TwoFactorAction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case twofactoraction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tfa.ID = int(value.Int64)
		case twofactoraction.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				tfa.Type = value.String
			}
		case twofactoraction.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				tfa.Version = int(value.Int64)
			}
		case twofactoraction.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tfa.Data); err != nil {
					return fmt.Errorf("unmarshal field data: %w", err)
				}
			}
		case twofactoraction.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiresAt", values[i])
			} else if value.Valid {
				tfa.ExpiresAt = value.Time
			}
		case twofactoraction.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				tfa.Code = value.String
			}
		default:
			tfa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TwoFactorAction.
// This includes values selected through modifiers, order, etc.
func (tfa *TwoFactorAction) Value(name string) (ent.Value, error) {
	return tfa.selectValues.Get(name)
}

// Update returns a builder for updating this TwoFactorAction.
// Note that you need to call TwoFactorAction.Unwrap() before calling this method if this TwoFactorAction
// was returned from a transaction, and the transaction was committed or rolled back.
func (tfa *TwoFactorAction) Update() *TwoFactorActionUpdateOne {
	return NewTwoFactorActionClient(tfa.config).UpdateOne(tfa)
}

// Unwrap unwraps the TwoFactorAction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tfa *TwoFactorAction) Unwrap() *TwoFactorAction {
	_tx, ok := tfa.config.driver.(*txDriver)
	if !ok {
		panic("ent: TwoFactorAction is not a transactional entity")
	}
	tfa.config.driver = _tx.drv
	return tfa
}

// String implements the fmt.Stringer.
func (tfa *TwoFactorAction) String() string {
	var builder strings.Builder
	builder.WriteString("TwoFactorAction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tfa.ID))
	builder.WriteString("type=")
	builder.WriteString(tfa.Type)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", tfa.Version))
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(fmt.Sprintf("%v", tfa.Data))
	builder.WriteString(", ")
	builder.WriteString("expiresAt=")
	builder.WriteString(tfa.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(tfa.Code)
	builder.WriteByte(')')
	return builder.String()
}

// TwoFactorActions is a parsable slice of TwoFactorAction.
type TwoFactorActions []*TwoFactorAction
