// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hedgehog125/project-reboot/ent/user"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (uc *UserCreate) SetUsername(s string) *UserCreate {
	uc.mutation.SetUsername(s)
	return uc
}

// SetContent sets the "content" field.
func (uc *UserCreate) SetContent(b []byte) *UserCreate {
	uc.mutation.SetContent(b)
	return uc
}

// SetMime sets the "mime" field.
func (uc *UserCreate) SetMime(s string) *UserCreate {
	uc.mutation.SetMime(s)
	return uc
}

// SetNonce sets the "nonce" field.
func (uc *UserCreate) SetNonce(b []byte) *UserCreate {
	uc.mutation.SetNonce(b)
	return uc
}

// SetKeySalt sets the "keySalt" field.
func (uc *UserCreate) SetKeySalt(b []byte) *UserCreate {
	uc.mutation.SetKeySalt(b)
	return uc
}

// SetPasswordHash sets the "passwordHash" field.
func (uc *UserCreate) SetPasswordHash(b []byte) *UserCreate {
	uc.mutation.SetPasswordHash(b)
	return uc
}

// SetPasswordSalt sets the "passwordSalt" field.
func (uc *UserCreate) SetPasswordSalt(b []byte) *UserCreate {
	uc.mutation.SetPasswordSalt(b)
	return uc
}

// SetHashTime sets the "hashTime" field.
func (uc *UserCreate) SetHashTime(b []byte) *UserCreate {
	uc.mutation.SetHashTime(b)
	return uc
}

// SetHashMemory sets the "hashMemory" field.
func (uc *UserCreate) SetHashMemory(b []byte) *UserCreate {
	uc.mutation.SetHashMemory(b)
	return uc
}

// SetHashKeyLen sets the "hashKeyLen" field.
func (uc *UserCreate) SetHashKeyLen(b []byte) *UserCreate {
	uc.mutation.SetHashKeyLen(b)
	return uc
}

// Mutation returns the UserMutation object of the builder.
func (uc *UserCreate) Mutation() *UserMutation {
	return uc.mutation
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uc.sqlSave, uc.mutation, uc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uc *UserCreate) Exec(ctx context.Context) error {
	_, err := uc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uc *UserCreate) ExecX(ctx context.Context) {
	if err := uc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uc *UserCreate) check() error {
	if _, ok := uc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "User.username"`)}
	}
	if _, ok := uc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "User.content"`)}
	}
	if _, ok := uc.mutation.Mime(); !ok {
		return &ValidationError{Name: "mime", err: errors.New(`ent: missing required field "User.mime"`)}
	}
	if _, ok := uc.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`ent: missing required field "User.nonce"`)}
	}
	if _, ok := uc.mutation.KeySalt(); !ok {
		return &ValidationError{Name: "keySalt", err: errors.New(`ent: missing required field "User.keySalt"`)}
	}
	if _, ok := uc.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "passwordHash", err: errors.New(`ent: missing required field "User.passwordHash"`)}
	}
	if _, ok := uc.mutation.PasswordSalt(); !ok {
		return &ValidationError{Name: "passwordSalt", err: errors.New(`ent: missing required field "User.passwordSalt"`)}
	}
	if _, ok := uc.mutation.HashTime(); !ok {
		return &ValidationError{Name: "hashTime", err: errors.New(`ent: missing required field "User.hashTime"`)}
	}
	if _, ok := uc.mutation.HashMemory(); !ok {
		return &ValidationError{Name: "hashMemory", err: errors.New(`ent: missing required field "User.hashMemory"`)}
	}
	if _, ok := uc.mutation.HashKeyLen(); !ok {
		return &ValidationError{Name: "hashKeyLen", err: errors.New(`ent: missing required field "User.hashKeyLen"`)}
	}
	return nil
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := uc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	uc.mutation.id = &_node.ID
	uc.mutation.done = true
	return _node, nil
}

func (uc *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: uc.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if value, ok := uc.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := uc.mutation.Content(); ok {
		_spec.SetField(user.FieldContent, field.TypeBytes, value)
		_node.Content = value
	}
	if value, ok := uc.mutation.Mime(); ok {
		_spec.SetField(user.FieldMime, field.TypeString, value)
		_node.Mime = value
	}
	if value, ok := uc.mutation.Nonce(); ok {
		_spec.SetField(user.FieldNonce, field.TypeBytes, value)
		_node.Nonce = value
	}
	if value, ok := uc.mutation.KeySalt(); ok {
		_spec.SetField(user.FieldKeySalt, field.TypeBytes, value)
		_node.KeySalt = value
	}
	if value, ok := uc.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeBytes, value)
		_node.PasswordHash = value
	}
	if value, ok := uc.mutation.PasswordSalt(); ok {
		_spec.SetField(user.FieldPasswordSalt, field.TypeBytes, value)
		_node.PasswordSalt = value
	}
	if value, ok := uc.mutation.HashTime(); ok {
		_spec.SetField(user.FieldHashTime, field.TypeBytes, value)
		_node.HashTime = value
	}
	if value, ok := uc.mutation.HashMemory(); ok {
		_spec.SetField(user.FieldHashMemory, field.TypeBytes, value)
		_node.HashMemory = value
	}
	if value, ok := uc.mutation.HashKeyLen(); ok {
		_spec.SetField(user.FieldHashKeyLen, field.TypeBytes, value)
		_node.HashKeyLen = value
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (ucb *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if ucb.err != nil {
		return nil, ucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ucb.builders))
	nodes := make([]*User, len(ucb.builders))
	mutators := make([]Mutator, len(ucb.builders))
	for i := range ucb.builders {
		func(i int, root context.Context) {
			builder := ucb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucb *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := ucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucb *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := ucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucb *UserCreateBulk) ExecX(ctx context.Context) {
	if err := ucb.Exec(ctx); err != nil {
		panic(err)
	}
}
